postgres:
  host: localhost
  port: 5432
  user: surveyor
  password: surveyor
  database: surveyor
mongodb:
  host: localhost
  port: 27017
  username: surveyor
  password: surveyor
  database: surveyor
kafka:
  host: localhost
  port: 9092
  topic: answers
manager:
  host: localhost
  port: 8080
requests:
  host: localhost
  port: 8081
statistics:
  host: localhost
  port: 8082