sudo: required
language: python
 - '3.6'
cache:
  directories:
    - $HOME/services
services:
  - docker
before_cache:
    # Save tagged docker images
    - >
      mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
      | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  bundler: true
  directories:
    - $HOME/docker
before_install:
  # Load cached docker images
  - source ~/virtualenv/python3.5/bin/activate
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
script:
  - python3 setup.py bdist_wheel
  - sudo apt-get install python-pip3
  - sudo pip3 install dist/survey_tester-1.0.0-py3-none-any.whl
  - make run
  - bash travis/sleep_if_needed.sh
  - survey_tester
