sudo: required
language: python
 - "3.6"
cache:
  directories:
    - $HOME/services
services:
  - docker
before_cache:
    # Save tagged docker images
    - >
      mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
      | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  bundler: true
  directories:
    - $HOME/docker
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
script:
  - python setup.py bdist_wheel
  - pip install dist/survey_tester-1.0.0-py2-none-any.whl
  - make run
  - python -m pip install --upgrade pip
  - bash travis/sleep_if_needed.sh
  - make test_run
